"""add product_name to order_items

Revision ID: 24932b4da6ab
Revises: 36b5db29122b
Create Date: 2026-03-18 20:26:18.759488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24932b4da6ab'
down_revision: Union[str, Sequence[str], None] = '36b5db29122b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_name', sa.String(length=100), nullable=False))
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
