"""add complete discount logic to products and categories

Revision ID: 2f24a7a15039
Revises: e4ec791be4d5
Create Date: 2026-03-12 18:10:49.468985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f24a7a15039'
down_revision: Union[str, Sequence[str], None] = 'e4ec791be4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
    op.add_column('categories', sa.Column('is_discount_cumulative', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('categories', sa.Column('is_discount_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
    op.add_column('products', sa.Column('is_discount_active', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_discount_active')
    op.drop_column('products', 'discount')
    op.drop_column('categories', 'is_discount_active')
    op.drop_column('categories', 'is_discount_cumulative')
    op.drop_column('categories', 'discount')
    # ### end Alembic commands ###
