"""add payment_type to orders

Revision ID: 32f2445c0056
Revises: f2ee8df1173f
Create Date: 2026-03-13 18:35:55.383374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f2445c0056'
down_revision: Union[str, Sequence[str], None] = 'f2ee8df1173f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    payment_enum = sa.Enum('CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'TRANSFER', 'VIRTUAL_WALLET', name='paymenttype')
    payment_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_type', payment_enum, nullable=False, server_default='CASH'))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_type')

    payment_enum = sa.Enum('CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'TRANSFER', 'VIRTUAL_WALLET', name='paymenttype')
    payment_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
