"""add logo_url to tenants

Revision ID: 36b5db29122b
Revises: f4ce807585f3
Create Date: 2026-03-16 19:45:18.550446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b5db29122b'
down_revision: Union[str, Sequence[str], None] = 'f4ce807585f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###
