"""add_user_soft_delete_and_order_item_history

Revision ID: ac1004dcaf04
Revises: e2f3a4b5c6d7
Create Date: 2026-05-08 21:59:49.484953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1004dcaf04'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_shifts_status'), table_name='cash_shifts')
    op.drop_index(op.f('ix_cash_shifts_tenant_id'), table_name='cash_shifts')
    op.drop_index(op.f('ix_cash_shifts_tenant_user_status'), table_name='cash_shifts')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.add_column('order_items', sa.Column('product_sku', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('product_barcode', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('category_name', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_orders_tenant_created'), table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_products_tenant_barcode'), table_name='products')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.create_unique_constraint('uq_product_tenant_barcode', 'products', ['tenant_id', 'barcode'])
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_constraint('uq_product_tenant_barcode', 'products', type_='unique')
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_products_tenant_barcode'), 'products', ['tenant_id', 'barcode'], unique=True)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_orders_tenant_created'), 'orders', ['tenant_id', 'created_at'], unique=False)
    op.drop_column('order_items', 'category_name')
    op.drop_column('order_items', 'product_barcode')
    op.drop_column('order_items', 'product_sku')
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_shifts_tenant_user_status'), 'cash_shifts', ['tenant_id', 'user_id', 'status'], unique=False)
    op.create_index(op.f('ix_cash_shifts_tenant_id'), 'cash_shifts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_shifts_status'), 'cash_shifts', ['status'], unique=False)
    # ### end Alembic commands ###
