"""add optional barcode to products

Revision ID: b7daaee32c1c
Revises: dacfc80494f5
Create Date: 2026-03-12 20:01:09.816720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7daaee32c1c'
down_revision: Union[str, Sequence[str], None] = 'dacfc80494f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
