"""add cash_shift_id to orders

Revision ID: f4ce807585f3
Revises: 71006484f0f4
Create Date: 2026-03-16 19:30:15.006828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ce807585f3'
down_revision: Union[str, Sequence[str], None] = '71006484f0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cashshiftstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_shifts_id'), 'cash_shifts', ['id'], unique=False)
    op.add_column('orders', sa.Column('cash_shift_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'cash_shifts', ['cash_shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'cash_shift_id')
    op.drop_index(op.f('ix_cash_shifts_id'), table_name='cash_shifts')
    op.drop_table('cash_shifts')
    # ### end Alembic commands ###
